### ISSUE TITLE
如何配置CDN

### ISSUE THREAD

**Issue by ghost** [acgx/ooi3#3]
自己和朋友玩。每次都从日本服务器下载文件太慢了。看了眼wiki没发现cdn的配置方法。请问改如何配置呢？

**Comment by kozora** [comment]
[配置方法](https://github.com/acgx/ooi3/wiki/OOI3%E7%9A%84CDN%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95)

**Comment by hello-maney** [comment]
对Linux不熟，请问下，ooi3这份教程不是独立的吧，还需要根据ooi2的教程配置一部分文件么？因为我只按照ooi3这份教程搭了后，打开页面只有提示“If you see this page, the nginx web server is successfully installed and working. Further configuration is required.”

**Comment by kozora** [comment]
@hello-maney 
you need add your domain on nginx conf

**Comment by Tsukumoyarei** [comment]
在nginx.conf配置了域名和DNS服务的网址之后，直接打开域名有ooi头像但是报502错，直接打开VPS的ip有nginx的初始界面，但是哪个都没法显示ooi界面。DNS解析已经将二级域名解析到VPS的ip上了，问题出在什么地方？
在安装过程中出现Running setup.py install for cffi ... error ，请问是直接无视还是需要手动安装？
已经解决了 安装了python3-dev就可以了
