### ISSUE TITLE
关于OOI_SECRET_KEY

### ISSUE THREAD

**Issue by dark-flames** [acgx/ooi3#5]
配置完成502
然后python3.4 ooi3.py异常是：
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.
求教OOI_SECRET_KEY应该怎么设置。
另外问一句，有没有docker的镜像？

**Comment by kozora** [comment]
如果仔细看过wiki的话，你不会有这个问题的
[https://github.com/acgx/ooi3/wiki/Config-OOI3-(Ubuntu-14.04)](配置supervisor)
