### ISSUE TITLE
OOI3系统是否会出现多开判定

### ISSUE THREAD

**Issue by ghost** [acgx/ooi3#6]
因为浏览器就那几种，IP就一个 假设A用poi，B也用 会不会被认为是同内核多开

**Comment by kozora** [comment]
你可以一个用POI，一个用浏览器

**Comment by ghost** [comment]
然而那是类似ooi那样公开的，我没法管理别人用什么浏览器，然而ooi如果没有因为多开封号估计这个就不会了吧

**Comment by kozora** [comment]
谨记不要作死就行了  不管你用啥工具
