### ISSUE TITLE
定制页面内容和其他一些问题

### ISSUE THREAD

**Issue by Tsukumoyarei** [acgx/ooi3#8]
ooi3里面，要定制的customize文件夹在什么位置？里面放置的html文档是否需要诸如<body>或者<head>之类的完整格式？
另外，ooi3需要像ooi2一样手动下载服务器图片和mainD2.swf吗？维护之后ooi3系统需要手动重新下载swf吗？

**Comment by kozora** [comment]
请仔细阅读WIKI
维护完之后只需要重启一下进程守护的OOI3即可

**Comment by Tsukumoyarei** [comment]
唔…我确定我已经读了ooi3和ooi2维基的所有页面，但是只有在ooi2的维基里找到了“OOI系统提供了有限的不修改源码而定制页面的功能，在customize目录中建立一些文件能够改变页面上的部分内容”这句。手动去一些目录看了一下也没有发现。难道是我遗漏了什么？

**Comment by kozora** [comment]
OOI2的自定义需要你自己实践来体会
OOI3的自定义直接修改即可显示

**Comment by Tsukumoyarei** [comment]
的确是疏忽了。ooi2的修改按照wiki是存放在名为customize的文件夹下，但是ooi3中这些文件被放在templates下，之前一直在找customize当然找不到了。
